Fix marshaling custom structures
arangodb/go-velocypack pull request #14
Opened 2020-03-16 18:42 UTC by informalict

1) Fix issue with Marshal custom fields in the structure.

2) 
Add tag "velocypack" for the field of the structure. It gives us the possibility to marshal and unmarshal different types. E. g:
`struct thing {
    Something int64 `json:"something,string" velocypack:"something,string,noquota"`
}`

We can Marsjal from int64 to string and Unmarshal from string to int64.
I need that in go-driver to build MerkleTree.
In the future, we should not use 'json' tag for velocypack protocol and maybe we will change that someday but of course there is a backward compatibility so if there is not 'velocypack' tag then we use 'json' tag.

2020-03-16 18:52 UTC, informalict commented on encoder.go
> +		if err = b.AddValue(NewSliceValue(vpack)); err != nil {
here is the fix for marshaling custom fields

2020-03-16 18:54 UTC, informalict commented on encoder_field.go
> +				if len(tag) == 0 {
for the time being len(tag) is always 0 but in go-driver I used that on the branch with Merkle tree:
type RevisionTree struct {
	Version  int                `json:"version"`
	RangeMin RevisionInt64      `json:"rangeMin,string" velocypack:"string,noquota"`
	RangeMax RevisionInt64      `json:"rangeMax,string" velocypack:"string,noquota"`
	Nodes    []RevisionTreeNode `json:"nodes"`
}

2020-03-17 07:14 UTC, ewoutp requested changes
I'm missing tests

2020-03-18 11:47 UTC, ewoutp reviewed
Custom marshaling test LGTM
I'm still missing tests for the velocypack tag.

2020-03-18 13:27 UTC, ewoutp approved these changes
2 minors, then LGTM

2020-03-18 13:27 UTC, ewoutp commented on test/encoder_custom_test.go
> +	require.Contains(t, string(marshaledStructure), "connectionString")
require -> assert

2020-03-18 13:27 UTC, ewoutp commented on test/encoder_custom_test.go
> +	require.Equal(t, expected, actual)
require -> assert

2020-03-18 13:55 UTC, merged